import type { UiComponentDef } from "@/types/registry"

export const UI_COMPONENTS: Record<string, UiComponentDef> = {
  button: { exportName: "Button", importPath: "button" },
  input: { exportName: "Input", importPath: "input" },
  textarea: { exportName: "Textarea", importPath: "textarea" },
  checkbox: { exportName: "Checkbox", importPath: "checkbox" },
  switch: { exportName: "Switch", importPath: "switch" },
  select: { exportName: "Select", importPath: "select" },
  label: { exportName: "Label", importPath: "label" },
  badge: { exportName: "Badge", importPath: "badge" },
  card: { exportName: "Card", importPath: "card" },
  form: { exportName: "Card", importPath: "card" },
  tabs: { exportName: "Tabs", importPath: "tabs" },
  separator: { exportName: "Separator", importPath: "separator" },
  skeleton: { exportName: "Skeleton", importPath: "skeleton" },
  "button-group": { exportName: "ButtonGroup", importPath: "button-group" },
  calendar: { exportName: "Calendar", importPath: "calendar" },
  field: { exportName: "Field", importPath: "field" },
  "native-select": {
    exportName: "NativeSelect",
    importPath: "native-select",
  },
  carousel: { exportName: "Carousel", importPath: "carousel" },
  item: { exportName: "Item", importPath: "item" },
  dialog: { exportName: "Dialog", importPath: "dialog" },
  drawer: { exportName: "Drawer", importPath: "drawer" },
  "hover-card": { exportName: "HoverCard", importPath: "hover-card" },
  command: { exportName: "Command", importPath: "command" },
  bubble: { exportName: "Bubble", importPath: "bubble" },
  message: { exportName: "Message", importPath: "message" },
  "message-scroller": {
    exportName: "MessageScroller",
    importPath: "message-scroller",
  },
  empty: { exportName: "Empty", importPath: "empty" },
  chart: { exportName: "ChartContainer", importPath: "chart" },
  kbd: { exportName: "Kbd", importPath: "kbd" },
  marker: { exportName: "Marker", importPath: "marker" },
  direction: { exportName: "DirectionProvider", importPath: "direction" },
  toast: { exportName: "toast", importPath: "sonner" },
  apiCall: { exportName: "Button", importPath: "button" },
}
